version: "3.7"

services:
  app:
    build:
      context: "."
    volumes:
      - "./app:/app"
      - "/app/node_modules"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docker-react.entrypoints=http"
      - "traefik.http.routers.docker-react.rule=Host(`docker-react.dev.localhost`)"
      - "traefik.http.routers.docker-react.middlewares=https-redirect@file"
      - "traefik.http.routers.docker-react-secure.entrypoints=https"
      - "traefik.http.routers.docker-react-secure.rule=Host(`docker-react.dev.localhost`)"
      - "traefik.http.routers.docker-react-secure.tls=true"
      - "traefik.http.services.docker-react.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"
    environment:
      - NODE_ENV=development

networks:
  default:
    external:
      name: traefik